# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: bug_fix

# The name of the component, or a single word describing the area of concern, (e.g. collector, target allocator, auto-instrumentation, opamp, github action)
component: operator

# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Fix Configuration marshalling for v1beta1 OpenTelemetryCollector instances.

# One or more tracking issues related to the change
issues: [3281]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  Previously, the v1beta1 OpenTelemetryCollector CR's config field was incorrectly
  marshalled, potentially causing issues when storing in etcd or retrieving via kubectl.
  This fix ensures that the config is properly marshalled, maintaining the correct
  structure and data types. For example, a config with nested maps and arrays will now
  be correctly preserved when stored and retrieved, instead of being flattened or
  losing structure.

  As an example, configuration like this:

  receivers:
      otlp:
        protocols:
          grpc:
          http:

  Would be retrieved from the Kubernetes cluster as:

  receivers:
      otlp:
        protocols:

  The specified protocols were not there anymore before this fix.